#define SECRET_SSID  "Box N°1"
#define SECRET_PASS  "MdP Box N°1"
#define SECRET_SSID2 "Box N°2"
#define SECRET_PASS2 "MdP Box N°2"
//#define SECRET_SSID3 "Nouvelle Box"
//#define SECRET_PASS3 "Mot de passe"